version: '3'
services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile  # Usamos un Dockerfile para construir la imagen
    container_name: my-telegram-bot
    volumes:
      - ./main.py:/app/main.py  # Monta el archivo de código local
      - ./requirements.txt:/app/requirements.txt  # Monta el archivo requirements.txt local
    working_dir: /app
    command: python main.py  # Comando para ejecutar el bot
    environment:
      - TELEGRAM_TOKEN=7112345223:AAH-DaqqEY3UGHbMcByushmzC-GuanqL6uA # Token del bot
      - API_KEY_GENAI=AIzaSyDd3OSCR9XjqkNoI52P-TMCHAH4y06NA0Q